version: '3.8'

name: SolvdExam

services:
  u-selenium:
    image: selenium/standalone-firefox:latest
    ports:
      - "4444:4444"
      - "7900:7900"
    shm_size: '2gb'
    restart: unless-stopped