# Infrastructure
url=<some-url>
# Browser settings (Carina requirements)
browser=firefox
browser_size=1920x1080
headless=false
# WebDriver configuration
selenium_url=http://localhost:4444/wd/hub
# Reporting & Core config
core_log_level=INFO
capabilities.pageLoadStrategy=eager